version: '3.7'

services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: union
      POSTGRES_PASSWORD: 87878847
      POSTGRES_DB: conductor
